apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce # can be claim by only one pod
    # - ReadOnlyMany # can be claim to read by many pods
    # - ReadWriteMany # can be claim to read and write by many pods
  hostPath: 
    path: /data
    type: DirectoryOrCreate

