apiVersion: apps/v1
kind: Deployment #Service , Jobs , 
metadata: 
  name: second-app-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key: app,operator: In, values: [second-app,first-app]}
  template: 
   # kind: Pod // PodTemplate always no need to specify
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: shoaib1698/kub-first-app:2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 10
        # - name:
          # image:
