version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: secret
      # - MONGO_INITDB_ROOT_USERNAME=max
      # - MONGO_INITDB_ROOT_PASSWORD=secret
      # env_file:
      # - ./env/mongo.env // if credential contains in the file
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile-dev
    #   args:
    #     - name=value
    ports:
      - '9000:9000'
    volumes:
      - logs:/app/logs
      - C:\LEARNING\JAVA\DevOps\Docker\Pratice Project\multi-01-starting-setup\backend:/app
      - /app/node_modules
    container_name: backend
    image: 'goals-node'
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - C:\LEARNING\JAVA\DevOps\Docker\Pratice Project\multi-01-starting-setup\frontend\src:/app/src
    container_name: frontend
    stdin_open: true
    tty: true

    image: 'goals-react'

    depends_on:
      - backend

volumes:
  data:
  logs:
